---
- name: "Configure Hostname and DNS"
  hosts: "nokia_srlinux"
  tasks:
    - name: "Configure the Hostname on Nokia"
      nokia.srlinux.config:
        update:
          - path: /system/name/host-name
            value: "{{ inventory_hostname }}"
        save_when: "changed"
    - name: "Configure DNS servers on Nokia"
      nokia.srlinux.config:
        replace:
          - path: /system/dns/server-list
            value:
              - "{{ item }}"
        save_when: "changed"
      loop: "{{ global['dns'] }}"
