---
- name: "Create New Users with Ansible"
  hosts: "arista_ceos"
  tasks:
    - name: "Create the ansible-ro user with password auth"
      arista.eos.eos_user:
        name: "ansible-ro"
        configured_password: "ansiblero123"
        role: "network-operator"
        state: "present"
