- name: "Create New User with Ansible"
  hosts: "nokia_srlinux"
  vars_files:
    - srl_secret.yml
  tasks:
    - name: "Create Users on Nokia Devices."
      vars:
        ansible_user: admin
        ansible_password: NokiaSrl1!
      nokia.srlinux.config:
        replace:
          - path: /system/aaa/authentication/user[username={{ item }}]
            value:
              password: "{{ lookup('vars' }}_password"
              superuser: "{% if 'rw' in item %}true{% else %}false{% endif %}"
        save_when: "changed"
      loop:
        - "ansible_rw"
        - "ansible_ro"
