---
interfaces:
  Ethernet1:
    ip_address: "172.31.1.3/31"
    description: "LEAF-TO-SPINE-CEOS-01-Ethernet4"
  Loopback0:
    ip_address: "10.100.1.2/32"
    description: "LOOPBACK FOR ROUTER ID"  
  Management0:
    ip_address: "198.51.100.13/24"
    description: "clab mgmt network"
