---
network_equipment:
  children:
    juniper_crpd:
juniper_crpd:
  hosts:
    crpd-01:
      ansible_host: 198.51.100.21
      ansible_network_os: "junipernetworks.junos.junos"
    crpd-02:
      ansible_host: 198.51.100.22
      ansible_network_os: "junipernetworks.junos.junos"
