---
- name: "Collect Network Facts using NAPALM"
  hosts: "srl-01"
  gather_facts: False
  tasks:
    - name: "Collect BGP NEIGHBOR NAPALM Facts"
      napalm_get_facts:
        optional_args: "{{ optional_args }}"
        dev_os: "{{ dev_os }}"
        filter:
          # - users
        - bgp_neighbors
      register: int_list
    - debug:
        var: int_list
