---
- name: "Collect Network Facts using NAPALM"
  hosts: "arista_ceos,nokia_srlinux"
  gather_facts: False
  tasks:
    - name: "Collect Interfaces NAPALM Facts"
      napalm_get_facts:
        optional_args: "{{ optional_args }}"
        dev_os: "{{ dev_os }}"
        filter:
          - interfaces
      register: interfaces
    - ansible.builtin.debug:
        var: interfaces
