---
network_equipment:
  children:
    arista_ceos:
arista_ceos:
  hosts:
    ceos-01:
      ansible_host: 198.51.100.11
    ceos-02:
      ansible_host: 198.51.100.12
    ceos-03:
      ansible_host: 198.51.100.13
  children:
    spines:
    leafs:
spines:
  hosts:
    ceos-01:
leafs:
  hosts:
    ceos-02:
    ceos-03:
